version: '3'
services:
  zookeeper:
    image: zookeeper:3.9.2
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "3001:3001"
    depends_on:
      - kafka
      - mongodb

  order-service:
    build:
      context: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - kafka
      - mongodb

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - inventory-service
      - order-service
